package com.homelink.coronatracker.model;

import java.util.HashMap;
import java.util.Map;

public class Countries {
    public static Map<String, String> doubleBraceMap  = new HashMap<String, String>() {{
        put("andorra", "ad");
        put("uae", "ae");
        put("afghanistan", "af");
        put("antigua and barbuda", "ag");
        put("anguilla", "ai");
        put("albania", "al");
        put("armenia", "am");
        put("netherlands antilles", "an");
        put("angola", "ao");
        put("antarctica", "aq");
        put("argentina", "ar");
        put("american samoa", "as");
        put("austria", "at");
        put("australia", "au");
        put("aruba", "aw");
        put("\u00c5land islands", "ax");
        put("azerbaijan", "az");
        put("bosnia and herzegovina", "ba");
        put("barbados", "bb");
        put("bangladesh", "bd");
        put("belgium", "be");
        put("burkina faso", "bf");
        put("bulgaria", "bg");
        put("bahrain", "bh");
        put("burundi", "bi");
        put("benin", "bj");
        put("saint barthélemy", "bl");
        put("st. barth", "bl");
        put("bermuda", "bm");
        put("brunei darussalam", "bn");
        put("brunei", "bn");
        put("bolivia, plurinational state of", "bo");
        put("bolivia", "bo");
        put("caribbean netherlands", "bq");
        put("brazil", "br");
        put("bahamas", "bs");
        put("bhutan", "bt");
        put("bouvet island", "bv");
        put("botswana", "bw");
        put("belarus", "by");
        put("belize", "bz");
        put("canada", "ca");
        put("cocos (keeling) islands", "cc");
        put("congo, the democratic republic of the", "cd");
        put("drc", "cd");
        put("car", "cf");
        put("central african republic", "cf");
        put("congo", "cg");
        put("switzerland", "ch");
        put("c\u00f4te divoire", "ci");
        put("ivory coast", "ci");
        put("cook islands", "ck");
        put("chile", "cl");
        put("cameroon", "cm");
        put("china", "cn");
        put("colombia", "co");
        put("costa rica", "cr");
        put("cuba", "cu");
        put("cape verde", "cv");
        put("cabo verde", "cv");
        put("cura\u00e7ao", "cw");
        put("christmas island", "cx");
        put("cyprus", "cy");
        put("czech republic", "cz");
        put("czechia", "cz");
        put("germany", "de");
        put("djibouti", "dj");
        put("denmark", "dk");
        put("dominica", "dm");
        put("dominican republic", "do");
        put("algeria", "dz");
        put("ecuador", "ec");
        put("estonia", "ee");
        put("egypt", "eg");
        put("western sahara", "eh");
        put("eritrea", "er");
        put("spain", "es");
        put("ethiopia", "et");
        put("europe", "eu");
        put("finland", "fi");
        put("fiji", "fj");
        put("falkland islands (malvinas)", "fk");
        put("micronesia, federated states of", "fm");
        put("faroe islands", "fo");
        put("faeroe islands", "fo");
        put("france", "fr");
        put("gabon", "ga");
        put("england", "gb-eng");
        put("northern ireland", "gb-nir");
        put("scotland", "gb-sct");
        put("wales", "gb-wls");
        put("uk", "gb");
        put("grenada", "gd");
        put("georgia", "ge");
        put("french guiana", "gf");
        put("guernsey", "gg");
        put("ghana", "gh");
        put("gibraltar", "gi");
        put("greenland", "gl");
        put("gambia", "gm");
        put("guinea", "gn");
        put("guadeloupe", "gp");
        put("equatorial guinea", "gq");
        put("greece", "gr");
        put("south georgia and the south sandwich islands", "gs");
        put("guatemala", "gt");
        put("guam", "gu");
        put("guinea-bissau", "gw");
        put("guyana", "gy");
        put("hong kong", "hk");
        put("heard island and mcdonald islands", "hm");
        put("honduras", "hn");
        put("croatia", "hr");
        put("haiti", "ht");
        put("hungary", "hu");
        put("indonesia", "id");
        put("ireland", "ie");
        put("israel", "il");
        put("isle of man", "im");
        put("india", "in");
        put("british indian ocean territory", "io");
        put("iraq", "iq");
        put("iran", "ir");
        put("iceland", "is");
        put("italy", "it");
        put("jersey", "je");
        put("jamaica", "jm");
        put("jordan", "jo");
        put("japan", "jp");
        put("kenya", "ke");
        put("kyrgyzstan", "kg");
        put("cambodia", "kh");
        put("kiribati", "ki");
        put("comoros", "km");
        put("saint kitts and nevis", "kn");
        put("n. korea, democratic peoples republic of", "kp");
        put("s. korea", "kr");
        put("korea, south", "kr");
        put("kuwait", "kw");
        put("cayman islands", "ky");
        put("channel islands", "ky");
        put("kazakhstan", "kz");
        put("laos", "la");
        put("lao peoples democratic republic", "la");
        put("lebanon", "lb");
        put("saint lucia", "lc");
        put("liechtenstein", "li");
        put("sri lanka", "lk");
        put("liberia", "lr");
        put("lesotho", "ls");
        put("lithuania", "lt");
        put("luxembourg", "lu");
        put("latvia", "lv");
        put("libya", "ly");
        put("morocco", "ma");
        put("monaco", "mc");
        put("moldova, republic of", "md");
        put("moldova", "md");
        put("montenegro", "me");
        put("saint martin", "mf");
        put("madagascar", "mg");
        put("marshall islands", "mh");
        put("macedonia, the former yugoslav republic of", "mk");
        put("north macedonia", "mk");
        put("mali", "ml");
        put("myanmar", "mm");
        put("mongolia", "mn");
        put("macao", "mo");
        put("northern mariana islands", "mp");
        put("martinique", "mq");
        put("mauritania", "mr");
        put("montserrat", "ms");
        put("malta", "mt");
        put("mauritius", "mu");
        put("maldives", "mv");
        put("malawi", "mw");
        put("mexico", "mx");
        put("malaysia", "my");
        put("mozambique", "mz");
        put("namibia", "na");
        put("new caledonia", "nc");
        put("niger", "ne");
        put("norfolk island", "nf");
        put("nigeria", "ng");
        put("nicaragua", "ni");
        put("netherlands", "nl");
        put("norway", "no");
        put("nepal", "np");
        put("nauru", "nr");
        put("niue", "nu");
        put("new zealand", "nz");
        put("oman", "om");
        put("panama", "pa");
        put("peru", "pe");
        put("french polynesia", "pf");
        put("papua new guinea", "pg");
        put("philippines", "ph");
        put("pakistan", "pk");
        put("poland", "pl");
        put("saint pierre and miquelon", "pm");
        put("pitcairn", "pn");
        put("puerto rico", "pr");
        put("palestine", "ps");
        put("portugal", "pt");
        put("palau", "pw");
        put("paraguay", "py");
        put("qatar", "qa");
        put("réunion", "re");
        put("romania", "ro");
        put("serbia", "rs");
        put("russian federation", "ru");
        put("russia", "ru");
        put("rwanda", "rw");
        put("saudi arabia", "sa");
        put("solomon islands", "sb");
        put("seychelles", "sc");
        put("sudan", "sd");
        put("sweden", "se");
        put("singapore", "sg");
        put("saint helena, ascension and tristan da cunha", "sh");
        put("slovenia", "si");
        put("svalbard and jan mayen islands", "sj");
        put("slovakia", "sk");
        put("sierra leone", "sl");
        put("san marino", "sm");
        put("senegal", "sn");
        put("somalia", "so");
        put("suriname", "sr");
        put("south sudan", "ss");
        put("sao tome and principe", "st");
        put("el salvador", "sv");
        put("sint maarten (dutch part)", "sx");
        put("sint maarten", "sx");
        put("syrian arab republic", "sy");
        put("syria", "sy");
        put("swaziland", "sz");
        put("eswatini", "sz");
        put("turks and caicos islands", "tc");
        put("turks and caicos", "tc");
        put("chad", "td");
        put("french southern territories", "tf");
        put("togo", "tg");
        put("thailand", "th");
        put("tajikistan", "tj");
        put("tokelau", "tk");
        put("timor-leste", "tl");
        put("turkmenistan", "tm");
        put("tunisia", "tn");
        put("tonga", "to");
        put("turkey", "tr");
        put("trinidad and tobago", "tt");
        put("tuvalu", "tv");
        put("taiwan", "tw");
        put("tanzania, united republic of", "tz");
        put("tanzania", "tz");
        put("ukraine", "ua");
        put("uganda", "ug");
        put("us minor outlying islands", "um");
        put("usa", "us");
        put("us", "us");
        put("uruguay", "uy");
        put("uzbekistan", "uz");
        put("holy see (vatican city state)", "va");
        put("vatican city", "va");
        put("saint vincent and the grenadines", "vc");
        put("st. vincent grenadines", "vc");
        put("venezuela, bolivarian republic of", "ve");
        put("venezuela", "ve");
        put("british virgin islands", "vg");
        put("virgin islands, british", "vg");
        put("virgin islands, u.s.", "vi");
        put("u.s. virgin islands", "vi");
        put("viet nam", "vn");
        put("vietnam", "vn");
        put("vanuatu", "vu");
        put("wallis and futuna islands", "wf");
        put("kosovo", "xk");
        put("samoa", "ws");
        put("yemen", "ye");
        put("mayotte", "yt");
        put("south africa", "za");
        put("zambia", "zm");
        put("zimbabwe", "zw");
        put("diamond princess", "ship-wheel");
        put("default", "flag");
    }};
}
